[package]
name = "inexor-rgf-plugin-tray"
description = "Inexor - Reactive Graph Flow - Plugin - Tray"
version = "0.6.0"
authors = ["Andreas Schaeffer <hanack@nooblounge.net>"]
edition = "2021"
license = "MIT"

[dependencies]
async-trait = "0.1"
indradb-lib = "3"
log = { version = "0.4", features = ["std", "serde"] }
log4rs = { version = "1.0", features = ["console_appender", "file_appender", "toml_format"]}
query_interface = "0.3"
rust-embed = { version = "6.2", features = ["debug-embed", "compression"] }
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
strum = { version = "0.24", features = ["derive"] }
strum_macros = "0.24"
tray-item = { git = "https://github.com/aschaeffer/tray-item-rs.git" }
toml = "0.5"
uuid = { version = "1.1", features = ["serde", "v4", "v5"] }

inexor-rgf-core-di = { version = "2.0", features = ["async"], git = "https://github.com/aschaeffer/inexor-rgf-core-di.git" }
inexor-rgf-core-model = { git = "https://github.com/aschaeffer/inexor-rgf-core-model.git" }
inexor-rgf-core-reactive = { git = "https://github.com/aschaeffer/inexor-rgf-core-reactive.git" }
inexor-rgf-core-plugins = { git = "https://github.com/aschaeffer/inexor-rgf-core-plugins.git" }

[lib]
# Plugins use crate-type cdylib
# https://doc.rust-lang.org/reference/linkage.html
# https://users.rust-lang.org/t/what-is-the-difference-between-dylib-and-cdylib/28847/3
crate-type = ["cdylib"]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
# 12MB -> 7.8MB
lto = true
# 7.8MB -> 4.5MB
strip = "symbols"
# 4.5MB -> 3.7MB
# opt-level = "z"
